class BLTSandwich: ...
class TurkeyAvocadoWrap: ...
class Chili: ...
class BaconCheeseBurger: ...
class FrenchOnionSoup: ...
class Menu: ...

name = "Chameleon Cafe"
address = "123 Fake St."

standard_lunch_entries = [BLTSandwich, TurkeyAvocadoWrap, Chili]
other_entries = [BaconCheeseBurger, FrenchOnionSoup]


def render_menu() -> Menu:
    # メニューを表示するコード
    pass
